# Generated by Django 4.2.23 on 2025-12-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='realt',
        ),
    ]
