# Generated by Django 4.2.23 on 2025-12-24 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_alter_cottage_options_alter_realtor_options'),
        ('users', '0004_alter_profile_realt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='realt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='realtors.realtor'),
        ),
    ]
