# Generated by Django 4.2.23 on 2025-09-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('office_adress', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, default='default.jpg', upload_to='realtors')),
                ('experience', models.IntegerField(default=0)),
                ('contacts', models.CharField(blank=True, max_length=200)),
                ('website', models.CharField(blank=True, max_length=400)),
                ('whatsapp', models.CharField(blank=True, max_length=100)),
                ('telegram', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
