# Generated by Django 4.2.23 on 2025-10-08 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cottage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=200)),
                ('land_area', models.IntegerField(default=0)),
                ('house_area', models.IntegerField(default=0)),
                ('floors', models.IntegerField(default=1)),
                ('walls', models.CharField(max_length=100)),
                ('bedrooms', models.IntegerField(default=1)),
                ('web_site', models.CharField(blank=True, max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('rlt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtors.realtor')),
            ],
        ),
    ]
