# Generated by Django 4.2.23 on 2025-12-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_cottage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cottage',
            options={'verbose_name': 'коттедж', 'verbose_name_plural': 'коттеджи'},
        ),
        migrations.AlterModelOptions(
            name='realtor',
            options={'ordering': ['title'], 'verbose_name': 'риелтор', 'verbose_name_plural': 'риелторы'},
        ),
    ]
