# Generated by Django 4.2.23 on 2025-09-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='telegram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='realtor',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
