# Generated by Django 4.2.23 on 2025-12-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('villages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infrastructure',
            options={'verbose_name': 'инфраструктуру', 'verbose_name_plural': 'инфраструктура'},
        ),
        migrations.AlterModelOptions(
            name='village',
            options={'ordering': ['title'], 'verbose_name': 'посёлок', 'verbose_name_plural': 'посёлки'},
        ),
    ]
