# Generated by Django 4.2.23 on 2025-09-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('featured_image', models.ImageField(blank=True, default='default.jpg', upload_to='villages')),
                ('direction', models.IntegerField(default=0)),
                ('distance', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('square', models.IntegerField(default=0)),
                ('land_price', models.IntegerField(default=0)),
                ('contacts', models.CharField(blank=True, max_length=200)),
                ('website', models.CharField(blank=True, max_length=400)),
                ('vote_total', models.IntegerField(default=0)),
                ('infrastructures', models.ManyToManyField(blank=True, to='villages.infrastructure')),
            ],
        ),
    ]
