# Generated by Django 4.2.23 on 2025-09-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='direction',
            field=models.CharField(max_length=100),
        ),
    ]
